Select t1.`ticket_id`,
  `internal_assignee`,
  `y42_product`,
  `product_ticket_type`,
  `organization_slug`,
  `forwarded_to_product`,
  `ticket_category`,
  `data_source`,
  `clickup_link`,
  `app_version`,
  `integration_name`,
  t3.`organization_id`,
  `requester_id`,
  `is_public`,
  `description`,
  `follower_ids`,
  `submitter_id`,
  `generated_timestamp`,
  t1.`id`,
  `group_id`,
  `type`,
  `collaborator_ids`,
  t1.`tags`,
  `has_incidents`,
  t1.`created_at`,
  `raw_subject`,
  `status`,
  t1.`updated_at`,
  `custom_fields`,
  t1.`url`,
  `priority`,
  `assignee_id`,
  `subject`,
  `satisfaction_rating_reason`,
  `satisfaction_rating_score`,
  `domain_names`,
  `organization_name`,
  `org_id`,
  `agent_wait_time_in_minutes`,
  `first_resolution_time_in_minutes`,
  `full_resolution_time_in_minutes`,
  `on_hold_time_in_minutes`,
  `reopens`,
  `replies`,
  `reply_time_in_minutes`,
  `requester_wait_time_in_minutes`,
  `solved_at`,
  time_to_react_in_minutes,
  t3.`email` AS requester_email,
  t3.name AS requester_name
                     from {{ ref('stg_zendesk_tickets') }} t1
                     JOIN {{ ref('stg_ticket_metrics') }} t2
                     ON t1.`ticket_id` = t2.`ticket_id`
                     JOIN {{ source('vdemo_public_cshackathoneumultiregion_main',
                     'Integrations_Y42_Analytics_Integrations_src_zendesk_users')}} t3
                     ON t1.`requester_id`=t3.id
